### ISSUE TITLE
node-pool version upgrade fails and removes state

### ISSUE THREAD

**Issue by mattford63** [terraform-providers/terraform-provider-google#2016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version

Discovered on 

```
Terraform v0.11.7
+ provider.google v1.15.0
+ provider.null v1.0.0
+ provider.random v1.3.1
```

Confirmed still an issue on

```
TF v0.11.8
provider.google v1.17.1
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

```tf
resource "google_container_cluster" "cluster" {
  name = "${var.env}-cluster"
  region = "${var.region}"
  project = "${var.project}"

  network = "${var.network}"
  subnetwork = "${var.subnetwork}"
  
  ip_allocation_policy {
    cluster_secondary_range_name = "${var.pod_range_name}"
    services_secondary_range_name = "${var.service_range_name}"
  }

  min_master_version = "${var.k8s_version}"
  #This is the work-around
  #node_version = "${var.k8s_version}"

  # This doesn't work like the current documentation
  # - https://www.terraform.io/docs/providers/google/r/container_node_pool.html
  
  node_pool {
    name       = "${var.env}-default-pool"
   #comment this out and uncomment node_version for a work-around
    version = "${var.k8s_version}"

    initial_node_count = "${var.default_pool_initial_node_count}"

    node_config {
      machine_type = "${var.default_pool_machine_type}"
      disk_size_gb = "${var.default_pool_disk_size_gb}"
      tags = ["${var.env}-cluster-default-pool"]
      oauth_scopes =  [
        "https://www.googleapis.com/auth/logging.write",
        "https://www.googleapis.com/auth/monitoring",
        "https://www.googleapis.com/auth/cloud-platform"
      ]
    }

    autoscaling {
      min_node_count = "${var.default_pool_autoscaling_min}"
      max_node_count = "${var.default_pool_autoscaling_max}"
    }

    management {
      auto_repair = "${var.default_pool_auto_repair}"
      auto_upgrade = "${var.default_pool_auto_upgrade}"
    }
  }

  master_authorized_networks_config {
    cidr_blocks = [
      {
        display_name = "Everything"
        cidr_block = "0.0.0.0/0"
      }
    ]
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "03:00"
    }
  }
  
  timeouts {
    create = "15m"
    delete = "25m"
  }
}
```

### Debug Output

```
module.dc-k8s.google_container_cluster.cluster: Modifying... (ID: dc-ci-cluster)
  min_master_version:  "1.10.4-gke.2" => "1.10.5-gke.4"
  node_pool.0.version: "1.10.4-gke.2" => "1.10.5-gke.4"

Error: Error applying plan:

1 error(s) occurred:

* module.dc-k8s.google_container_cluster.cluster: 1 error(s) occurred:

* google_container_cluster.cluster: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Removing plan.bin...
```

### Panic Output

https://gist.github.com/fffa7cf94d3445f0b0fc8e5c159cf4f1

### Expected Behavior

When upgrading the pool version I expect the  pool to upgrade (we tried this due to security alerts issued by Google).

### Actual Behavior

A plan works without issue but the apply fails hard removing the resource from the TF state, but luckily not the infrastructure itself.

Any subsequent plans will then create another cluster....

By restoring a previous version of the tf.state and moving the node version out of the node pool and into the cluster config we are able to successfully upgrade.  i.e comment and uncomment the annotated lines in the TF above.

**Comment by directionless** [comment]
This might be a dup of https://github.com/terraform-providers/terraform-provider-google/issues/2022

**Comment by paddycarver** [comment]
This is a panic, relevant portion is here:

```
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: panic: interface conversion: interface {} is nil, not string
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: goroutine 13 [running]:
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: github.com/terraform-providers/terraform-provider-google/google.nodePoolUpdate(0xc4202412d0, 0x2293fc0, 0xc4200b4000, 0xc42029d650, 0xc420664770, 0xc, 0xa, 0x42, 0xc42045c701)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/google/resource_container_node_pool.go:659 +0x152d
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: github.com/terraform-providers/terraform-provider-google/google.resourceContainerClusterUpdate(0xc4202412d0, 0x2293fc0, 0xc4200b4000, 0x0, 0xc42008f288)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/google/resource_container_cluster.go:1074 +0x6e2
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4201facb0, 0xc42016e460, 0xc420524060, 0x2293fc0, 0xc4200b4000, 0x1, 0xc42041ff50, 0xc42041ff50)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:233 +0x259
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc4202404d0, 0xc42016e410, 0xc42016e460, 0xc420524060, 0x35e9000, 0x0, 0x18)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xa4
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420488a00, 0xc420489c00, 0xc42037fe40, 0x0, 0x0)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x57
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: reflect.Value.call(0xc42047a780, 0xc4204964c8, 0x13, 0x25cac0a, 0x4, 0xc420048f20, 0x3, 0x3, 0x0, 0x0, ...)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: reflect.Value.Call(0xc42047a780, 0xc4204964c8, 0x13, 0xc420461720, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: net/rpc.(*service).call(0xc420486840, 0xc42016e140, 0xc42049c820, 0xc42047c200, 0xc420489520, 0x213b360, 0xc420489c00, 0x16, 0x213b3a0, 0xc42037fe40, ...)
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: created by net/rpc.(*Server).ServeCodec
2018-09-10T16:16:34.344+0100 [DEBUG] plugin.terraform-provider-google_v1.15.0_x4: 	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by rileykarson** [comment]
I believe that this was fixed when we made a widespread change to our expand functions. If this is still an issue can you reproduce it on a recent `2.X` series release and file a new issue?
