### ISSUE TITLE
nodepool create fails with component "kube-apiserver" from endpoint "gke-XXX" is unhealthy

### ISSUE THREAD

**Issue by jamielennox** [terraform-providers/terraform-provider-google#2034]
When creating a container cluster with a seperate nodepool google initially returns an error. The nodepool eventually stabilizes and the cluster works but the initial response is a failure.

I'm pretty sure this is actually a failure of the Google APIs but we either need to figure out how to support the case on terraform if this is normal or report it to google (which i'm hoping someone here will know how to do). 

Sample terraform

```main.tf
locals {
  name = "jamie-test"
  project = "XXXXXXX"
  zone = "australia-southeast1-a"

}

resource "google_container_cluster" "cluster" {
  project = "${local.project}"

  min_master_version = "1.10"

  name = "${local.name}"

  initial_node_count = "2"

  zone = "${local.zone}"

  monitoring_service = "monitoring.googleapis.com/kubernetes"
  logging_service    = "logging.googleapis.com/kubernetes"

# disable all basic and certificate auth - only auth via OpenID is available
  master_auth {
    username = ""
    password = ""
    client_certificate_config {
      issue_client_certificate = false
    }
  }

  lifecycle {
    ignore_changes  = ["initial_node_count", "node_config", "node_version"]
  }

  remove_default_node_pool = true

  # https://github.com/terraform-providers/terraform-provider-google/issues/1648
  network = "projects/${local.project}/global/networks/default"

  addons_config {
    horizontal_pod_autoscaling {
      disabled = "false"
    }

    http_load_balancing {
      disabled = "false"
    }

    kubernetes_dashboard {
      disabled = "false"
    }

    network_policy_config {
      disabled = "false"
    }
  }

  maintenance_policy {
    daily_maintenance_window {
      start_time = "17:00"
    }
  }
}

resource "google_container_node_pool" "nodepool" {
  project = "${local.project}"
  name    = "${local.name}-nodes"
  zone    = "${local.zone}"

  initial_node_count = "2"

  autoscaling {
    min_node_count = "2"
    max_node_count = "5"
  }

  cluster = "${google_container_cluster.cluster.name}"

  management {
    auto_repair  = true
    auto_upgrade = true
  }

  node_config {
    image_type   = "COS"
    preemptible  = "true"
    machine_type = "n1-standard-2"

    oauth_scopes = [
      "https://www.googleapis.com/auth/devstorage.read_only",
      "https://www.googleapis.com/auth/logging.write",
      "https://www.googleapis.com/auth/monitoring",
    ]
  }
}
```

```
google_container_node_pool.nodepool: Still creating... (13m40s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* google_container_node_pool.nodepool: 1 error(s) occurred:

* google_container_node_pool.nodepool: Error waiting for creating GKE NodePool: All cluster resources were brought up, but the cluster API is reporting that: component "kube-apiserver" from endpoint "gke-00b00249c866f68660a1-c14f" is unhealthy
goroutine 356355245 [running]:
runtime/debug.Stack(0xc015ac741b, 0x3, 0x2dc1b7a)
	third_party/go/gc/src/runtime/debug/stack.go:24 +0xa7
google3/cloud/kubernetes/engine/common/errdesc.(*GKEErrorDescriptor).createErr(0x55277e0, 0xc0001c8000)
	cloud/kubernetes/engine/common/error_desc.go:199 +0x26
google3/cloud/kubernetes/engine/common/errdesc.(*GKEErrorDescriptor).WithDetail(0x55277e0, 0x312a4a0, 0xc0113e4500, 0xc0113e4500, 0x3121ac0)
	cloud/kubernetes/engine/common/error_desc.go:166 +0x40
google3/cloud/kubernetes/engine/common/healthcheck.glob..func1.1(0x0, 0xc0035c3e00)
	cloud/kubernetes/engine/common/healthcheck.go:141 +0x7bb
google3/cloud/kubernetes/engine/common/call.WithTimeout(0x318d620, 0xc01da74690, 0x77359400, 0x8bb2c97000, 0xc025db9d08, 0xc01da74690, 0xc01cc23580)
	cloud/kubernetes/engine/common/call.go:36 +0x153
google3/cloud/kubernetes/engine/common/healthcheck.glob..func1(0x318d620, 0xc01da74690, 0xc020340450, 0xc005db8a80, 0xc013e4fa00, 0x8bb2c97000, 0x0, 0x0)
	cloud/kubernetes/engine/common/healthcheck.go:137 +0x33b
google3/cloud/kubernetes/engine/server/deploy/deploy.upgradeMasterAndVerify.func3(0xc0054bfb80, 0x318d560, 0xc0024b7d40, 0x7fbc9833b5b8, 0xc002022480, 0xc01e6e4800, 0x0, 0xc02182bef0, 0xc020340450, 0xc005db8a80, ...)
	cloud/kubernetes/engine/server/deploy/update.go:969 +0x1b3
google3/cloud/kubernetes/engine/server/deploy/deploy.upgradeMasterAndVerify(0x318d560, 0xc0024b7d40, 0xc0054bfb80, 0x7fbc9833b5b8, 0xc002022480, 0xc020340450, 0xc01e6e4800, 0x0, 0x1, 0x0, ...)
	cloud/kubernetes/engine/server/deploy/update.go:975 +0x13f
google3/cloud/kubernetes/engine/server/deploy/deploy.(*Deployer).recreateMasterReplicas.func2(0x0, 0x0)
	cloud/kubernetes/engine/server/deploy/update.go:546 +0x23c
google3/cloud/kubernetes/engine/common/errors.CollectFns.func1(0xc00417a540, 0xc014568190)
	cloud/kubernetes/engine/common/errors.go:162 +0x27
created by google3/cloud/kubernetes/engine/common/errors.CollectFns
	cloud/kubernetes/engine/common/errors.go:162 +0x82
.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

<img width="620" alt="screen shot 2018-09-12 at 9 12 23 pm" src="https://user-images.githubusercontent.com/416057/45421740-5da03280-b6d1-11e8-9020-ce76ddbacfa6.png">

**Comment by jamielennox** [comment]
Duplicate of #2022
