### ISSUE TITLE
New common operation handling panics on upstream errors

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#2912]
API:
```
-----------------------------------------------------
2019/01/22 22:36:31 [DEBUG] Google API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 503 Service Unavailable
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39"
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Tue, 22 Jan 2019 22:36:31 GMT
Expires: Tue, 22 Jan 2019 22:36:31 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Code: '2045967775581918469'"
   }
  ],
  "code": 503,
  "message": "Code: '2045967775581918469'"
 }
}
-----------------------------------------------------
```

Error:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccComputeBackendService_withMaxConnections

------- Stderr: -------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x17601ea]

goroutine 282 [running]:
github.com/terraform-providers/terraform-provider-google/google.(*ComputeOperationWaiter).Error(0xc42084f1a0, 0x1ebf820, 0x0)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/google/compute_operation.go:21 +0x2a
github.com/terraform-providers/terraform-provider-google/google.CommonRefreshFunc.func1(0xc420ceff20, 0x1, 0x0, 0x0, 0x1, 0x0)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/google/common_operation.go:100 +0xd2
github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc42104e4e0, 0xc420478cb0, 0xc420ff9d80, 0xc420027c80, 0xc420ac87e0, 0xc420ac87d8)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x4e0
created by github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1d0
```

**Comment by rileykarson** [comment]
Adding to `2.0.0` milestone to make sure this is fixed before that release; it's pretty rough behaviour.
