### ISSUE TITLE
Crash in ComputeOperationWaiter

### ISSUE THREAD

**Issue by maikzumstrull** [terraform-providers/terraform-provider-google#317]
```
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: panic: runtime error: invalid memory address or nil pointer dereference
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: [signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x1bcb5c4]
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: goroutine 2109 [running]:
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/google.(*ComputeOperationWaiter).RefreshFunc.func1(0xc420348f20, 0xc421b1e300, 0x0, 0x1, 0
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/google/compute_operation.go:27 +0x64
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:1
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: created by github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitFo
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:1
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: panic: interface conversion: interface {} is nil, not *compute.Operation
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: goroutine 2088 [running]:
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/google.computeOperationWaitTime(0xc4208023c0, 0x0, 0xc4203782e0, 0x12, 0x1f82f37, 0x1d, 0x
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/google/compute_operation.go:88 +0x2da
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/google.computeSharedOperationWaitZoneTime(0xc4208023c0, 0x1d53f80, 0x0, 0xc4203782e0, 0x12
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/google/compute_shared_operation.go:34 +0xb3
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/google.computeSharedOperationWaitZone(0xc4208023c0, 0x1d53f80, 0x0, 0xc4203782e0, 0x12, 0x
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/google/compute_shared_operation.go:28 +0x9d
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/google.resourceComputeInstanceGroupManagerCreate(0xc4205733b0, 0x1d44da0, 0xc4208023c0, 0x
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/google/resource_compute_instance_group_manager.go:255 +0x95c
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4218366c0, 0xc421
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420ac1e30, 0xc421
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc4203b6d20,
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /Users/mzumstrull/go/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/plugin/resource_provider.g
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: reflect.Value.call(0xc42034b9e0, 0xc42166d758, 0x13, 0x1f685be, 0x4, 0xc421e6ff20, 0x3, 0x3, 0x1faa8a8, 0xc4204b9ee8, ...)
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: reflect.Value.Call(0xc42034b9e0, 0xc42166d758, 0x13, 0xc4204b9f20, 0x3, 0x3, 0xc4204b9f0c, 0x180001, 0x5300000000)
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: net/rpc.(*service).call(0xc421eb6f00, 0xc421eb6ec0, 0xc421d06dd8, 0xc42222cc00, 0xc420378320, 0x1c5fde0, 0xc42081aa60, 0x16, 0x1c5fe20, 0xc42180aa1
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /usr/local/Cellar/go/1.8.3/libexec/src/net/rpc/server.go:387 +0x144
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google: created by net/rpc.(*Server).ServeCodec
2017/08/10 12:40:53 [DEBUG] plugin: terraform-provider-google:  /usr/local/Cellar/go/1.8.3/libexec/src/net/rpc/server.go:481 +0x404
```

The problem seems to be that in https://github.com/terraform-providers/terraform-provider-google/blob/52daf4097ad4528a8428aa1bf079afa961f17ea9/google/compute_operation.go#L27 `w.Op` can be `nil` in at least one codepath related to `resourceComputeInstanceGroupManagerCreate`. Haven't found out why exactly that happens yet.

Doesn't necessarily affect any released build, we run a patched master build because of https://github.com/terraform-providers/terraform-provider-google/issues/141.

**Comment by maikzumstrull** [comment]
`op` is already `nil` when it is created in this block: https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_group_manager.go#L225-L234

The `nil` check in https://github.com/terraform-providers/terraform-provider-google/blob/master/google/compute_shared_operation.go#L37-L38 is broken, "a pointer with a nil value" is different from "the nil interface".

**Comment by maikzumstrull** [comment]
I think it might be that in https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_group_manager.go#L227 you're creating a new scoped `err` variable  but never check it - the check in https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_instance_group_manager.go#L247-L249 covers the parent scope?

**Comment by maikzumstrull** [comment]
Yes, replacing those `:=` with `=` makes the crash go away.

**Comment by rileykarson** [comment]
Thanks for the report @maikzumstrull!

I've submitted a PR fixing that issue in `google_compute_instance_group_manager`, as well as a couple other places where it was happening; sorry you had to run into that issue, and thanks again for helping to catch it before a release!
