### ISSUE TITLE
Convert fails if a 429 error is received during a Read on Project

### ISSUE THREAD

**Issue by rileykarson** [terraform-providers/terraform-provider-google#3227]
Occurs in `2.2.0` for sure, and probably from `2.0.0` onwards

```hcl
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccProjectIamPolicy_basicAuditConfig
=== PAUSE TestAccProjectIamPolicy_basicAuditConfig
=== CONT  TestAccProjectIamPolicy_basicAuditConfig

------- Stderr: -------
panic: reflect: call of reflect.Value.NumField on zero Value

goroutine 134 [running]:
reflect.flag.mustBe(0x0, 0x19)
	/opt/goenv/versions/1.11.5/src/reflect/value.go:207 +0xb4
reflect.Value.NumField(0x0, 0x0, 0x0, 0x1e65d00)
	/opt/goenv/versions/1.11.5/src/reflect/value.go:1222 +0x34
github.com/terraform-providers/terraform-provider-google/google.setOmittedFields(0x1b76d80, 0x0, 0x19bc280, 0xc00064cc88)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/google/convert.go:38 +0x1f8
github.com/terraform-providers/terraform-provider-google/google.Convert(0x1b76d80, 0x0, 0x19bc280, 0xc00064cc88, 0x0, 0x0)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/google/convert.go:25 +0xdb
github.com/terraform-providers/terraform-provider-google/google.(*CommonOperationWaiter).SetOp(0xc00064cc88, 0x1b76d80, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/google/common_operation.go:60 +0x4d
github.com/terraform-providers/terraform-provider-google/google.CommonRefreshFunc.func1(0xc0005d1f50, 0xc0005d1d98, 0x2, 0x1, 0x1, 0x0)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/google/common_operation.go:108 +0x90
github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState.func1(0xc0000ad0e0, 0xc000478620, 0xc00058c940, 0xc00008d3e0, 0xc0006a9610, 0xc0006a95f8)
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:103 +0x29e
created by github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource.(*StateChangeConf).WaitForState
	/opt/teamcity-agent/work/b03f1a13170573f8/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform/helper/resource/state.go:80 +0x1b9
```

**Comment by rileykarson** [comment]
Closing as outdated.
