### ISSUE TITLE
data source google_compute_subnetwork crashes when using self_link

### ISSUE THREAD

**Issue by brondum** [terraform-providers/terraform-provider-google#4784]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* If an issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to "hashibot", a community member has claimed the issue already.

### Terraform Version
Terraform v0.12.12
+ provider.google v2.18.1

### Affected Resource(s)
data.google_compute_subnetwork

### Terraform Configuration Files

```tf
provider "google" {
  credentials = "${file("bestseller-es-lowtest-685f-72e531c83686.json")}"
  project     = "bestseller-es-lowtest-685f"
  region      = "europe-west4-a"
  version     = "~> 2.18.1"
}

variable "vpc_subnetwork_name" {
  default = "projects/network-host-project-5361/regions/europe-west4/subnetworks/bestseller-es-lowtest-1"
}

variable "cluster_secondary_range_name" {
  default = "pods"
}



// retrieve subnet cidrs for ip-masq-agent settings
data "google_compute_subnetwork" "subnet" {
  self_link   = "projects/network-host-project-5361/regions/europe-west4/subnetworks/bestseller-es-lowtest-1"
  #name = "bestseller-es-lowtest-1"
  #project = "network-host-project-5361"
  #region = "europe-west4"
}


output "host_network_cidr" {
  value = data.google_compute_subnetwork.subnet.ip_cidr_range
}

output "pod_network_cidr" {
  value = {
    for subnet in data.google_compute_subnetwork.subnet.secondary_ip_range:
    subnet.range_name => subnet.ip_cidr_range
    if subnet.range_name == var.cluster_secondary_range_name
  }
}
```

### Panic Output
```
Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range [6] with length 6
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4:
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: goroutine 16 [running]:
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/terraform-providers/terraform-provider-google/google.GetLocationalResourcePropertiesFromSelfLinkString(0xc000042ba0, 0x5b, 0x9, 0x29726e0, 0xc00053e2a0, 0x1, 0x409c140, 0xc0007fd920, 0x1, 0xc0003fd710)
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/google/self_link_helpers.go:146 +0x14f
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/terraform-providers/terraform-provider-google/google.getResourcePropertiesFromSelfLinkOrSchema(0xc000530cb0, 0xc0000d2000, 0x1, 0xc0003fd780, 0x102ca91, 0x2f9f8a0, 0xc0003fd790, 0x2aa5040, 0xc0003fd800, 0x100bbf6, ...)
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/google/self_link_helpers.go:109 +0x81
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/terraform-providers/terraform-provider-google/google.GetRegionalResourcePropertiesFromSelfLinkOrSchema(...)
2019-10-31T10:59:02.025+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/google/self_link_helpers.go:104
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/terraform-providers/terraform-provider-google/google.dataSourceGoogleComputeSubnetworkRead(0xc000530cb0, 0x2b3ea00, 0xc0000d2000, 0xc000530cb0, 0x0)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/google/data_source_google_compute_subnetwork.go:78 +0x72
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0xc0000ed400, 0xc0007fd920, 0x2b3ea00, 0xc0000d2000, 0xc00010b098, 0x1, 0x0)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/resource.go:398 +0x88
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0xc000387700, 0xc0003fd9d8, 0xc0007fd920, 0xc0007fd920, 0x0, 0x0)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/helper/schema/provider.go:446 +0x8f
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00009a7c0, 0x32f0220, 0xc00068c420, 0xc000672f40, 0xc00009a7c0, 0xc00068c420, 0xc0005e3a80)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/helper/plugin/grpc_provider.go:1036 +0x44e
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler(0x2e9f920, 0xc00009a7c0, 0x32f0220, 0xc00068c420, 0xc0003a4ae0, 0x0, 0x32f0220, 0xc00068c420, 0xc0005c8fc0, 0x108)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.0.0/internal/tfplugin5/tfplugin5.pb.go:3225 +0x217
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000be160, 0x33206e0, 0xc00007b200, 0xc000397b00, 0xc000111680, 0x40a5c10, 0x0, 0x0, 0x0)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x460
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: google.golang.org/grpc.(*Server).handleStream(0xc0000be160, 0x33206e0, 0xc00007b200, 0xc000397b00, 0x0)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd97
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003a4d0, 0xc0000be160, 0x33206e0, 0xc00007b200, 0xc000397b00)
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2019-10-31T10:59:02.026+0100 [DEBUG] plugin.terraform-provider-google_v2.18.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
2019/10/31 10:59:02 [ERROR] <root>: eval: *terraform.EvalReadData, err: rpc error: code = Unavailable desc = transport is closing
2019/10/31 10:59:02 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/10/31 10:59:02 [TRACE] [walkRefresh] Exiting eval tree: data.google_compute_subnetwork.subnet
2019/10/31 10:59:02 [TRACE] vertex "data.google_compute_subnetwork.subnet": visit complete
2019/10/31 10:59:02 [TRACE] vertex "data.google_compute_subnetwork.subnet": dynamic subgraph encountered errors
2019/10/31 10:59:02 [TRACE] vertex "data.google_compute_subnetwork.subnet": visit complete
2019/10/31 10:59:02 [TRACE] dag/walk: upstream of "output.pod_network_cidr" errored, so skipping
2019/10/31 10:59:02 [TRACE] dag/walk: upstream of "provider.google (close)" errored, so skipping
2019/10/31 10:59:02 [TRACE] dag/walk: upstream of "output.host_network_cidr" errored, so skipping
2019/10/31 10:59:02 [TRACE] dag/walk: upstream of "root" errored, so skipping
2019-10-31T10:59:02.028+0100 [DEBUG] plugin: plugin process exited: path=/Users/peter.brondum/dev/temp/.terraform/plugins/darwin_amd64/terraform-provider-google_v2.18.1_x4 pid=55763 error="exit status 2"
2019/10/31 10:59:02 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2019/10/31 10:59:02 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2019-10-31T10:59:02.029+0100 [DEBUG] plugin: plugin exited
```
### Expected Behavior
Should grab the actual info for that subnet.

### Actual Behavior
Terraform crashes.
If i dont use the self link but use the `name`, `project` & `region` fields it works.

### Steps to Reproduce
1. `terraform apply`

### References

* #0000

**Comment by brondum** [comment]
Okay just a i posted i figured what the error was.
You need to prefix it with the whole url like: `https://www.googleapis.com/compute/v1/`  (which you dont need in other resources).
