### ISSUE TITLE
Segfault in google_container_cluster since 3.10.0

### ISSUE THREAD

**Issue by juzna** [terraform-providers/terraform-provider-google#5768]
`terraform plan` fails with `Error: rpc error: code = Unavailable desc = transport is closing`.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If an issue is assigned to the `modular-magician` user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If an issue is assigned to a user, that user is claiming responsibility for the issue. If an issue is assigned to `hashibot`, a community member has claimed the issue already.

### Terraform Version

```
Terraform v0.12.21
+ provider.google-beta v3.10.0
```

It works when I pin it to 3.9.0:
```tf
# providers.tf
terraform {
  ...
  required_providers {
    google-beta = "3.9.0"
  }
}
```

### Affected Resource(s)

* google_container_cluster

### Terraform Configuration Files

The config is pretty much irrelevant, since the crash occurs on refresh when loading the existing resource from GKE API.

The config below is enough to reproduce the problem, but the cluster must already exist:

```tf
resource "google_container_cluster" "cluster" {
  provider = google-beta
  name     = "foo"
}
```

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x284b39f]
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5:
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: goroutine 97 [running]:
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: github.com/terraform-providers/terraform-provider-google-beta/google-beta.flattenClusterAutoscaling(0x0, 0x3196729, 0xa, 0x2b9ecc0)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:2739 +0x62f
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: github.com/terraform-providers/terraform-provider-google-beta/google-beta.resourceContainerClusterRead(0xc000566620, 0x2dafee0, 0xc000636c00, 0xc000566620, 0x0)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/google-beta/resource_container_cluster.go:1259 +0xebd
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0005b8680, 0xc0007023c0, 0x2dafee0, 0xc000636c00, 0xc00000f150, 0x0, 0x0)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:455 +0x119
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0005ac8f8, 0x35fe300, 0xc000736180, 0xc0007021e0, 0xc0005ac8f8, 0xc000736180, 0xc000849b30)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3d8
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x310fea0, 0xc0005ac8f8, 0x35fe300, 0xc000736180, 0xc0000aa7e0, 0x0, 0x35fe300, 0xc000736180, 0xc000740800, 0x2612)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x217
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000532780, 0x3634920, 0xc000533380, 0xc00013a400, 0xc0005fe9f0, 0x44a8570, 0x0, 0x0, 0x0)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/google.golang.org/grpc/server.go:1024 +0x4f4
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: google.golang.org/grpc.(*Server).handleStream(0xc000532780, 0x3634920, 0xc000533380, 0xc00013a400, 0x0)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/google.golang.org/grpc/server.go:1313 +0xd97
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000af3b0, 0xc000532780, 0x3634920, 0xc000533380, 0xc00013a400)
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/google.golang.org/grpc/server.go:722 +0xbb
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-02-26T14:51:19.689+0100 [DEBUG] plugin.terraform-provider-google-beta_v3.10.0_x5: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google-beta/vendor/google.golang.org/grpc/server.go:720 +0xa1
2020-02-26T14:51:19.692+0100 [DEBUG] plugin: plugin process exited: path=/Users/juzna/projects/infra/autobooking/sandbox/.terraform/plugins/darwin_amd64/terraform-provider-google-beta_v3.10.0_x5 pid=21244 error="exit status 2"
```

### Steps to Reproduce

1. `terraform plan` or `terraform import google_container_cluster.cluster $ID`

**Comment by juzna** [comment]
It works fine on a newly created cluster, but crashes on old ones. I'm still trying to figure out what's the difference between them...

**Comment by juzna** [comment]
Comparison of `terraform import` using old cluster (crashes) vs newly created cluster (works): https://gist.github.com/juzna/441b1aa363b54db5cd8a275e14a4e1ed; for some reason there seem to be multiple outputs interleaved, which makes the JSON mangled :/
