### ISSUE TITLE
terraform crash.

### ISSUE THREAD

**Issue by jplogos** [terraform-providers/terraform-provider-google#5907]
We see terraform crash as below. 
This is similar to an old issue #2112 [](https://github.com/terraform-providers/terraform-provider-google/issues/2112)

Can you please advise on this?

**Terraform v0.11.12**

**Crash Output:** (complete crash log attached).
[crash.log](https://github.com/terraform-providers/terraform-provider-google/files/4343070/crash.log)

2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: panic: runtime error: invalid memory address or nil pointer dereference
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc47747]
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: goroutine 38 [running]:
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/libvirt.resourceLibvirtDomainRead(0xc42041a460, 0xe193e0, 0xc42000f918, 0x0, 0x0)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/libvirt/resource_libvirt_domain.go:761 +0x1277
2020/03/17 09:01:23 [TRACE] dag/walk: upstream errored, not walking "module.cn_lg20ecx3s1_ac1d1.module.puppet.null_resource.provision_puppet"
2020-03-17T09:01:23.795Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-libvirt
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc4203ec000, 0xc42041c0f0, 0xe193e0, 0xc42000f918, 0xc4203f0638, 0xc4203d9701, 0x80000000000)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:352 +0x17e
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4203ec620, 0xc42041c0a0, 0xc42041c0f0, 0x7fe0fc1db000, 0x0, 0xc4203ec620)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2020/03/17 09:01:23 [TRACE] dag/walk: upstream errored, not walking "provider.null (close)"
2020/03/17 09:01:23 [TRACE] dag/walk: upstream errored, not walking "root"
2020/03/17 09:01:23 [DEBUG] plugin: waiting for all plugin processes to complete...
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4203a7d80, 0xc4203e94d0, 0xc4203e9610, 0x0, 0x0)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/home/abuild/rpmbuild/BUILD/terraform-provider-libvirt-0.5.1/_build/src/github.com/dmacvicar/terraform-provider-libvirt/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: reflect.Value.call(0xc4202f6e40, 0xc4202e2380, 0x13, 0xffb233, 0x4, 0xc420323f20, 0x3, 0x3, 0x20002, 0xc42036871c, ...)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/reflect/value.go:434 +0x905
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: reflect.Value.Call(0xc4202f6e40, 0xc4202e2380, 0x13, 0xc420368720, 0x3, 0x3, 0xd7e1df, 0x1, 0x0)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/reflect/value.go:302 +0xa4
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: net/rpc.(*service).call(0xc4202d8cc0, 0xc4202da500, 0xc4202e4440, 0xc4202eb180, 0xc4203f84a0, 0xe1dee0, 0xc4203e94d0, 0x16, 0xe1df20, 0xc4203e9610, ...)
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/net/rpc/server.go:381 +0x142
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: created by net/rpc.(*Server).ServeCodec
2020-03-17T09:01:23.795Z [DEBUG] plugin.terraform-provider-libvirt: 	/usr/lib/golang/src/net/rpc/server.go:475 +0x36b
2020-03-17T09:01:23.795Z [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2020-03-17T09:01:23.806Z [DEBUG] plugin.terraform-provider-ironic_v1.0.1: 2020/03/17 09:01:23 [ERR] plugin: plugin server: accept unix /tmp/plugin126685887: use of closed network connection
2020-03-17T09:01:23.806Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2020/03/17 09:01:23 [ERR] plugin: plugin server: accept unix /tmp/plugin189714604: use of closed network connection
2020-03-17T09:01:23.806Z [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2020/03/17 09:01:23 [DEBUG] plugin: waiting for all plugin processes to complete...
2020-03-17T09:01:23.806Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-local_v1.1.0_x4
2020-03-17T09:01:23.806Z [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2020/03/17 09:01:23 [ERR] plugin: plugin server: accept unix /tmp/plugin882977270: use of closed network connection
2020-03-17T09:01:23.806Z [DEBUG] plugin.terraform: local-exec-provisioner (internal) 2020/03/17 09:01:23 [DEBUG] plugin: waiting for all plugin processes to complete...
2020-03-17T09:01:23.806Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform
2020-03-17T09:01:23.806Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-template_v1.0.0_x4
2020-03-17T09:01:23.806Z [DEBUG] plugin: plugin process exited: path=/usr/local/bin/terraform
2020-03-17T09:01:23.807Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-external_v1.0.0_x4
2020-03-17T09:01:23.807Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-null_v1.0.0_x4
2020-03-17T09:01:23.807Z [DEBUG] plugin: plugin process exited: path=/opt/velocix/infra/terraform/terraform-provider-ironic_v1.0.1

**Comment by jplogos** [comment]
wrong provider.
